### ISSUE TITLE
API updates

### ISSUE THREAD

**Issue by teuben** [teuben/ascl-tools#3]
the API/readme file is still sparse:
- list the public keywords
- curl example update?

**Comment by siddharm** [comment]
Hi Peter,

Yep, I spent yesterday trying to fix my vim setup -- it was hanging at the
terminal, and not letting me edit anything, but now it works 👍🏾. I have
some examples, and I'll update the docs today.

Thanks,
Siddha Mavuram

**Comment by siddharm** [comment]
Finished updating README 👍🏾👍🏾
