### ISSUE TITLE
Fill out API publically accessible field descriptions

### ISSUE THREAD

**Issue by siddharm** [teuben/ascl-tools#7]
Alice will write up short descriptions for fields to go in the API README.

**Comment by ASCLnet** [comment]
Field name | Field type | Description
-- | -- | --
abstract | text | Brief description of the code
ascl_id | varchar (8) | The human-friendly version of an ASCL id. Format is YYMM.### where YY is the year, MM is the month, and ### is an incrementing integer padded with zeroes.
bibcode | varchar (19) | A 19-digit bibliographic code that allows the entry to be uniquely identified in several indexing services such as the SAO/NASA Astrophysics Data System (ADS). More information about this identifier   appears on the ADS website (http://doc.adsabs.harvard.edu/abs_doc/help_pages/data.html#bibcodes).
citation_method | text | How the code should be cited, according to the author(s) or website of the code. As a courtesy to the code author(s), please check the code website to verify the citation preference.
credit | text | Normalized list of author names, not serialized
described_in | text | Paper in which the code is described ("code paper"); this is typically a refereed paper written by the software author(s), though may not be refereed if there is a "used in" paper
site_list | text | Serialized array of websites associated with a code, including a download site
time_updated | timestamp (Default 0000-00-00 00:00:00) | Date/time code was last updated
title | text | Title of the code, usually with a "short" title to start, followed by a colon and the longer name
topic_id | mediumint (8) | phpBB topic id for "discuss" link to the discussion forum
used_in | text | Refereed paper in which the code is used but not described, which may be, and is often, written by someone other than the software author. This is provided as verification that the software has been used in a refereed research article, particularly when there is no code paper or the code paper has not been refereed.
views | mediumint (8) | Number of times an individual code page has been visited

**Comment by siddharm** [comment]
Still need one for "keywords"

**Comment by ASCLnet** [comment]
keywords: Serialized array in a text field of words or phrases that are associated with the entry. Currently this field is used to identify software that is associated with NASA (National Aeronautics and Space Administration) and HITS (Heidelberg Institute for Theoretical Studies).

**Comment by siddharm** [comment]
Fixed!
